.PHONY: all nmc_monitor_client nmc_monitor_consumer

all: nmc_monitor_client nmc_monitor_consumer

nmc_monitor_client:
	$(MAKE) -C nmc_monitor_client

nmc_monitor_consumer:
	$(MAKE) -C nmc_monitor_consumer
